remote_theme: just-the-docs/just-the-docs

title: "Documentación Bazaar - Grupo 3"

nav_external_links:
  - title: User API
    url: https://github.com/bazaar-g3/bazaar-user-api/blob/main/README.md
  - title: Catalog API
    url: https://github.com/bazaar-g3/bazaar-catalog-api/blob/main/README.md
  - title: Orders API
    url: https://github.com/bazaar-g3/bazaar-orders-api/blob/main/README.md
  - title: Payment API
    url: https://github.com/bazaar-g3/bazaar-payment-api/blob/main/README.md
  - title: Notifications API
    url: https://github.com/bazaar-g3/bazaar-notifications-api/blob/main/README.md
  - title: Backoffice
    url: https://github.com/bazaar-g3/bazaar-backoffice/blob/main/README.md
  - title: Mobile
    url: https://github.com/bazaar-g3/bazaar-mobile/blob/main/README.md
